apiVersion: v1
kind: Service
metadata:
  name: liqo-broker-aggregator
spec:
  ports:
  - name: grpc-api
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: liqo-broker-catalog
  type: ClusterIP
