apiVersion: v1
kind: Service
metadata:
  name: liqo-broker-catalog
spec:
  ports:
  - name: http-api
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: liqo-broker-catalog
  type: ClusterIP
