apiVersion: v1
kind: Pod
metadata:
  labels:
    app: liqo-broker
  name: liqo-broker
spec:
  containers:
  - args:
    - --with-aggregator
    - --with-catalog
    - --with-orchestrator
    image: capacitorset/liqo-broker
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - /bin/grpc_health_probe
        - -addr=:8081
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: broker
    ports:
    # Catalog/orchestrator HTTP
    - containerPort: 8000
      protocol: TCP
    # Aggregator gRPC
    - containerPort: 7000
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/grpc_health_probe
        - -addr=:8081
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi
  restartPolicy: Always
